### PR TITLE
Use async read operations to cope with slow sending clients

### PR DESCRIPTION
**Pull request by Chelaris182**

### CODE REVIEW

**Comment by vtortola** [comment]
Hi, can you provide some explanation about your changes?

Also, you are blocking on asynchronous code (calling .Result on tasks), something un-recommended.

**Comment by Chelaris182** [comment]
sorry, I thought the code is self-explanatory :)
the main idea is to remove blocking calls from ReadMessageAsync to properly handle situations when the client sends first few bytes of the header, for example, 4 bytes of the first 6.

There is no need to implement synchronous Read methods as ReadMessageAsync.Result essentially has the same effect - it blocks the calling thread waiting for a result of async background operation. It isn't recommended to implement async operations via sync calls, but the opposite chain of calls isn't a problem.

**Comment by vtortola** [comment]
Well, no, it is unrecommended to wrap async over sync and also viceversa. The recommendation is to provide both ways without wrapping, and that is why there are two paths that are almost independent where almost all calls are blocking or asynchronous: Stephen Toub : [Should I expose synchronous wrappers for asynchronous methods?](http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx).

I understand your concern about slow clients, but you are picturing a scenario where the client is so ridiculously slow than sending a dozen of bytes even when the first bytes of the header are already in the buffer is going to waste a thread from the thread pool.

**Comment by Chelaris182** [comment]
slow clients are quite common for the world of mobile clients

**Comment by Chelaris182** [comment]
and in case you are afraid of sync wrappers, I'd suggest to remove sync wrappers from the library as they won't work in high-load scenarios anyway

**Comment by vtortola** [comment]
Hi, I am not removing the sync wrappers. The scenario is unlikely, although after some thought it may lead to thread starvation if clients start sending incomplete headers, so a `ParseHeadAsync` path will need to be added.

**Comment by Chelaris182** [comment]
absolutely, http negotiation also must be changed to async operations.

so, what about this PR?

**Comment by Chelaris182** [comment]
btw: the sync wrappers will cause thread starvation anyway, so I don't understand how anyone can use them in server implementation :)

**Comment by vtortola** [comment]
There was life before asynchronous programming, not all projects are web, or have many users.

Probably the only needed change is to create a `ParseHeaderAsync` counterpart.

**Comment by Chelaris182** [comment]
if they don't have many users then proposed sync wrappers will work absolutely fine

**Comment by vtortola** [comment]
As I explained before, if sync methods need to be provided, the recommendation is to provide the real thing and not a wrapper.

**Pull request closed without merging**
