### PR TITLE
HTTP Header Case Insensitive Compare

### PR DESCRIPTION
**Pull request by jeepMan79**
Hello,

We are using this library in our application and recently discovered that the HTTP headers like "WebSocket-Version" was coming across "Websocket-Version", notice the lowercase "S".  This was causing the handshake not to complete in the websocket library.

The changes are to make the HTTP header validation case insensitive.

Thank You.

### CODE REVIEW

**Comment by vtortola** [comment]
I see. Which client is sending such header?

Why not just making the header collection case insensitive? There is a [constructor](https://msdn.microsoft.com/en-us/library/ms132072(v=vs.110).aspx) that accepts a comparer, and [StringComparer.OrdinalIgnoreCase](https://msdn.microsoft.com/en-us/library/system.stringcomparer.ordinalignorecase(v=vs.110).aspx) can be used.

```cs
public HttpHeadersCollection()
{
    _headers = new Dictionary<String, String>(StringComparer.OrdinalIgnoreCase); 
}
```

This change should fix the problem all together.

**Comment by vtortola** [comment]
I checked in the change, let me know if you find any further issue: https://github.com/vtortola/WebSocketListener/commit/ddf66a7f5aa33ddd88ae41145e5746f639a4ab10

Cheers.

**Comment by vtortola** [comment]
I merged your pr and fixed the test cases. Making the `_headers` dictionary case insensitive was a simpler fix, but it came with the burden of making the lookup a little bit slower, so I decided to drop that solution.

Thanks for taking the time in reporting this :+1:

**Comment by jeepMan79** [comment]
Thanks Vtortola.  Great library BTW!

**Pull request merged**
