### PR TITLE
Supporting Mono.Android

### PR DESCRIPTION
**Pull request by michaeled**
Hey Val,

I'm creating this pull request to start a discussion. I've modified the WebSocketListener projects to include a Mono.Android ProjectGuid. So, they could be referenced by my Mono.Android projects. I've also added a very poor service locator to remove the dependency on System.Web.

The goal here is to have your library running on Mono.Android, and possibly iOS when I'm ready for testing. How else would you have approached this problem?

### CODE REVIEW

**Comment by vtortola** [comment]
Hi Michael,

That is interesting, I didn´t even expect WebSocketListener to run on mobile :) Didn´t you have issues with the dataflow library? 

I see you want to remove the dependency on `System.Web` but in your `DroidHttpServices` class you are still using `HttpUtility.UrlDecode(url)`, the method that you replaced. Which is exactly the issue with `System.Web`? If these two methods are a problem, we can implement a replacement inside `vtortola.WebSocketListener.dll` assembly, but let´s not add another additional assembly.

Also, can you explain why the multiple GUID? I am totally lost in mobile dev :)

By the way, I am going on holidays on Friday morning, so I won´t be around for more than a week.

**Comment by michaeled** [comment]
I thought that might look confusing! I should have included a more complete example. 

The vtortola.* projects are referencing `System.Web` to get the `HttpUtility.UrlDecode(url)` method. In Mono, `HttpUtility.UrlDecode(url)` is in the `System.Web.Services` assembly. So, I include that in my Android project, instead.

On the subject of the project GUIDs, I must confess I don't have a strong grasp on this part.
Your projects target a class library, and I can only reference PCLs or other Android Class Libraries. I get around this by adding the Mono.Android Class Library GUID. So, now it acts as a full framework class library and a Mono.Android class library. I'm sure this isn't the right thing to do.

I would think that your projects should be changed to PCLs? What do you think?

Here's a link to Visual Studio Project Guids for a reference:
http://www.codeproject.com/Reference/720512/List-of-Visual-Studio-Project-Type-GUIDs

**Comment by vtortola** [comment]
I will check if I can include the Url.Decode source into the project and investigate those projects guid next week when Iam back.

**Comment by vtortola** [comment]
Is  [WebUtility.UrlDecode](https://msdn.microsoft.com/en-us/library/system.net.webutility.urldecode(v=vs.110).aspx) available in Mono Android in the same assembly than in .NET?

**Pull request closed without merging**
