### PR TITLE
Support for dotnet rc2 (including merges from main project)

### PR DESCRIPTION
**Pull request by StefH**
Support for dotnet rc2 (including merges from main project)

```
-     Indeed a lot of changes, however some of these come from the https://github.com/papci/WebSocketListener project. I just continued on that one, fixed all merge issues and upgraded to dotnet rc.
- 
-     I did not test on mono, but this framework will be obsolete in some time when dotnet core is more available. (Maybe it will still work because .net 4.5 is still supported ?)
- 
-     Do you have a test-server or more test-code running to check if all still works.
- 
-     A separate branch, I did not think of that...
- 
-     In case of more questions, please ask...
```

### CODE REVIEW

**Comment by vtortola** [comment]
This belongs in a fork :)

**Comment by StefH** [comment]
You mean a separate **branch** ?

There is no danger in this pull-request, there are no critical code-changes, it's only made compatible with dotnet rc2 core which will help a lot of projects which are 'core' and want to use your project.

Also running this on linux would mean a big pro for some projects.

**Comment by StefH** [comment]
New PR : https://github.com/vtortola/WebSocketListener/pull/68

**Comment by StefH** [comment]
Obsolete...

**Pull request closed without merging**
