### PR TITLE
Code reformat/cleanup + fixed ReSharper warnings for "vtortola.WebSockets.Rfc6455" project.

### PR DESCRIPTION
**Pull request by StefH**
Code reformat/cleanup + fixed ReSharper warnings for "vtortola.WebSockets.Rfc6455" project.

Created a helper class with defines for BufferLengths and used this in the constructor from 'WebSocketConnectionRfc6455' class.

```c#
internal static class BufferLen
{
    public const int Header = 14;
    public const int Control = 125;
    public const int Pong = 125;
    public const int Ping = 8;
    public const int X = 10; // ?
    public const int Key = 4;
    public const int Close = 2;
}
```

This is done to replace *magic* values with defines and make it possible to reuse these defines in the project.

### CODE REVIEW

**Comment by vtortola** [comment]
Hi, thanks! I am at a the airport on my way to my holidays 😊 I will take a look when I come back.

**Comment by vtortola** [comment]
Due a commit I did, I cannot merge this automatically. I have to schedule time to do it. Thanks again!

**Comment by StefH** [comment]
If you need help, please contact me.

**Comment by StefH** [comment]
I've checked, and there are 4 files which have conflicting changes, but these are easy to merge. Just take your version instead of mine.

**Comment by vtortola** [comment]
Hi,  I included some of the changes already. I will include others later. Thanks a million.

**Pull request closed without merging**
