### PR TITLE
Feature: WebSocketClient, Transports

### PR DESCRIPTION
**Pull request by deniszykov**
Hi! We use your library in our project (Online Game). But, unfortunately, it had some serious drawbacks for working in high-performance applications. Blocking operations in the thread pool #77 #76 #75,  buffer pool does not work on Mono and inability to use in-memory transport on Unix platforms for efficient reverse-proxing. I was given time to refactor your library and I solved these problems. Below is a list of improvements and known issues. You can reformat my source code back to your style, if you want. Projects are in VS2017 format and target two platforms net45 and netstandard1.3. Tests are xUnit.

Major Features:
- WebSocketClient
    - TLS Support
    - Auto IPv6 address resolution
    - Same features and options as WebSocketListener
- Transports
    - TCP, Unix Sockets, Named Pipes (why not)
    - Socket is abstracted as NetworkConnection
    - Graceful disconnection
    - Fine tuning with WebSocketListenerOptions.Transports collection extensions

Minor Features:
- Fully async API (it is strongly discouraged to use synchronous API with IO operations)
- Logging via abstract ILogger
- No additional dependencies (ServiceModel, TPL Dataflow)
- New Headers<HeadersT> collections with fast access to known headers
- custom BufferManager, and use of BufferManager in all operations with buffers
- More unit-tests
- WebSocketListener can now listen multiple endpoints from different transports
- Pings now processed in batches or could be manually batched and sent (WebSocket.PingAsync)
- WebSocketMessageWriteStream now can be gracefully closed with CloseAsync()
- Tested to work under load

Lost Features:
- UWP target platform
- Sync API on WebSocket and Streams
- Cookies collection on WebSocketHttpRequest (class is not removed)
- Removed potentially dangerous feature 'RemoveBOM' on WSWriteStream.Write. Refactored default WriteStringAsync(), ReadStringAsync methods to use UTF-8 without BOM

Known Problems:
- WebSocketDeflateStream uses sync Stream methods, it should be rewritten to fully support async operations
- Mono can't handle IPv6 Dual Mode sockets properly (exception in Socket.RemoteEndPoint and Socket.LocalEndPoint)

### CODE REVIEW

**Comment by StefH** [comment]
Maybe better to just start a new github + NuGet project instead of this PR ? In that way you can take up further development as a new owner?

**Comment by deniszykov** [comment]
@StefH  probably it is good idea to start new project. Any idea how to call it? :)

**Comment by StefH** [comment]
`WebSocketListener`

;-)

**Comment by vtortola** [comment]
@deniszykov go for it 👍

**Comment by vtortola** [comment]
This project started as a home project, and unfortunately I never had the chance to use it at work. That and the lack of time are the main reasons why it take ages for me to review and tests PRs or accommodate requests; I have to test with home apps that not always reproduce completely real conditions, and it takes lot of time. And as I have other software things going on in my free time , I cannot maintain this as you guys need.

If you are going to create a new repo, create an organization so it is not a personal project anymore :)

**Comment by deniszykov** [comment]
I have a similar problem. I will not have time to maintain such project. Fixing bugs - yes. Adding features - hardly. Unfortunately, I did not even have time to fix the documentation. I decided to just to publish my changes as [Nuget](https://www.nuget.org/packages/deniszykov.WebSocketListener/) package. Any help with docs are welcome.

**Comment by vtortola** [comment]
@deniszykov I am thinking I am going to revert this repo to https://github.com/vtortola/WebSocketListener/commit/5f10cffc557701fcb1d8820264d6f3e9a4aac45a and then indicate this project is discontinued and a link to yours. 

Would that affect or mess with you in anyway? I believe that as long you don't do a pull from this origin it should be fine.

**Comment by deniszykov** [comment]
@vtortola okay, I will try to maintain this repository as long as I can.

**Comment by vtortola** [comment]
👍

**Pull request closed without merging**
